(let* ((n (read))
       (x (read))
       (an (sort (loop repeat n collect (read)) #'<)))
  (loop with l = 0 and r = (1- n)
        while (<= l r)
        for m = (floor (+ l r) 2)
        do (cond ((< x (elt an m))
                  (setf r (1- m)))
                 ((< (elt an m) x)
                  (setf l (1+ m)))
                 (t
                  (return (princ "Yes"))))
        finally (princ "No")))
